// <auto-generated />
using System;
using FoodTour_WebAdmin.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodTour_WebAdmin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310160117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.DishModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = "d-001",
                            ImageUrl = "dish_01.jpg",
                            Price = 120000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-002",
                            ImageUrl = "dish_02.jpg",
                            Price = 50000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-003",
                            ImageUrl = "dish_03.jpg",
                            Price = 120000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-004",
                            ImageUrl = "dish_04.jpg",
                            Price = 160000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-005",
                            ImageUrl = "dish_05.jpg",
                            Price = 120000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-006",
                            ImageUrl = "dish_01.jpg",
                            Price = 110000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-007",
                            ImageUrl = "dish_02.jpg",
                            Price = 110000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-008",
                            ImageUrl = "dish_03.jpg",
                            Price = 110000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-009",
                            ImageUrl = "dish_04.jpg",
                            Price = 80000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-010",
                            ImageUrl = "dish_05.jpg",
                            Price = 110000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-011",
                            ImageUrl = "dish_01.jpg",
                            Price = 100000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-012",
                            ImageUrl = "dish_02.jpg",
                            Price = 60000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-013",
                            ImageUrl = "dish_03.jpg",
                            Price = 60000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-014",
                            ImageUrl = "dish_04.jpg",
                            Price = 110000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-015",
                            ImageUrl = "dish_05.jpg",
                            Price = 50000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-016",
                            ImageUrl = "dish_01.jpg",
                            Price = 250000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-017",
                            ImageUrl = "dish_02.jpg",
                            Price = 180000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-018",
                            ImageUrl = "dish_03.jpg",
                            Price = 150000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-019",
                            ImageUrl = "dish_04.jpg",
                            Price = 60000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-020",
                            ImageUrl = "dish_05.jpg",
                            Price = 80000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-021",
                            ImageUrl = "dish_01.jpg",
                            Price = 450000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-022",
                            ImageUrl = "dish_02.jpg",
                            Price = 320000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-023",
                            ImageUrl = "dish_03.jpg",
                            Price = 200000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-024",
                            ImageUrl = "dish_04.jpg",
                            Price = 130000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-025",
                            ImageUrl = "dish_05.jpg",
                            Price = 380000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-026",
                            ImageUrl = "dish_01.jpg",
                            Price = 70000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-027",
                            ImageUrl = "dish_02.jpg",
                            Price = 60000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-028",
                            ImageUrl = "dish_03.jpg",
                            Price = 90000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-029",
                            ImageUrl = "dish_04.jpg",
                            Price = 80000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-030",
                            ImageUrl = "dish_05.jpg",
                            Price = 70000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-031",
                            ImageUrl = "dish_01.jpg",
                            Price = 65000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-032",
                            ImageUrl = "dish_02.jpg",
                            Price = 120000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-033",
                            ImageUrl = "dish_03.jpg",
                            Price = 95000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-034",
                            ImageUrl = "dish_04.jpg",
                            Price = 75000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-035",
                            ImageUrl = "dish_05.jpg",
                            Price = 55000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-036",
                            ImageUrl = "dish_01.jpg",
                            Price = 30000.0,
                            ShopId = "s-008"
                        },
                        new
                        {
                            Id = "d-037",
                            ImageUrl = "dish_02.jpg",
                            Price = 25000.0,
                            ShopId = "s-008"
                        },
                        new
                        {
                            Id = "d-038",
                            ImageUrl = "dish_03.jpg",
                            Price = 35000.0,
                            ShopId = "s-008"
                        },
                        new
                        {
                            Id = "d-039",
                            ImageUrl = "dish_04.jpg",
                            Price = 40000.0,
                            ShopId = "s-008"
                        },
                        new
                        {
                            Id = "d-040",
                            ImageUrl = "dish_05.jpg",
                            Price = 45000.0,
                            ShopId = "s-008"
                        });
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.DishTranslationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DishId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("LanguageCode");

                    b.ToTable("DishTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DishId = "d-001",
                            LanguageCode = "vi",
                            Name = "Càng ghẹ rang muối"
                        },
                        new
                        {
                            Id = 2,
                            DishId = "d-002",
                            LanguageCode = "vi",
                            Name = "Hào nướng phô mai"
                        },
                        new
                        {
                            Id = 3,
                            DishId = "d-003",
                            LanguageCode = "vi",
                            Name = "Nghêu hấp Thái"
                        },
                        new
                        {
                            Id = 4,
                            DishId = "d-004",
                            LanguageCode = "vi",
                            Name = "Bạch tuộc nướng muối ớt"
                        },
                        new
                        {
                            Id = 5,
                            DishId = "d-005",
                            LanguageCode = "vi",
                            Name = "Chem chép xào tỏi"
                        },
                        new
                        {
                            Id = 6,
                            DishId = "d-006",
                            LanguageCode = "vi",
                            Name = "Ốc hương rang muối ớt"
                        },
                        new
                        {
                            Id = 7,
                            DishId = "d-007",
                            LanguageCode = "vi",
                            Name = "Ốc hương xào bơ"
                        },
                        new
                        {
                            Id = 8,
                            DishId = "d-008",
                            LanguageCode = "vi",
                            Name = "Sò huyết xào tỏi"
                        },
                        new
                        {
                            Id = 9,
                            DishId = "d-009",
                            LanguageCode = "vi",
                            Name = "Nghêu hấp sả"
                        },
                        new
                        {
                            Id = 10,
                            DishId = "d-010",
                            LanguageCode = "vi",
                            Name = "Ốc mỡ xào me"
                        },
                        new
                        {
                            Id = 11,
                            DishId = "d-011",
                            LanguageCode = "vi",
                            Name = "Lưỡi vịt Sapo"
                        },
                        new
                        {
                            Id = 12,
                            DishId = "d-012",
                            LanguageCode = "vi",
                            Name = "Ốc tỏi nướng mắm"
                        },
                        new
                        {
                            Id = 13,
                            DishId = "d-013",
                            LanguageCode = "vi",
                            Name = "Răng mực rang muối"
                        },
                        new
                        {
                            Id = 14,
                            DishId = "d-014",
                            LanguageCode = "vi",
                            Name = "Bò lúc lắc"
                        },
                        new
                        {
                            Id = 15,
                            DishId = "d-015",
                            LanguageCode = "vi",
                            Name = "Khoai tây chiên"
                        },
                        new
                        {
                            Id = 16,
                            DishId = "d-016",
                            LanguageCode = "vi",
                            Name = "Lẩu dê nấm"
                        },
                        new
                        {
                            Id = 17,
                            DishId = "d-017",
                            LanguageCode = "vi",
                            Name = "Dê nướng tảng"
                        },
                        new
                        {
                            Id = 18,
                            DishId = "d-018",
                            LanguageCode = "vi",
                            Name = "Dê xào lăn"
                        },
                        new
                        {
                            Id = 19,
                            DishId = "d-019",
                            LanguageCode = "vi",
                            Name = "Cháo dê đậu xanh"
                        },
                        new
                        {
                            Id = 20,
                            DishId = "d-020",
                            LanguageCode = "vi",
                            Name = "Tiết canh dê"
                        },
                        new
                        {
                            Id = 21,
                            DishId = "d-021",
                            LanguageCode = "vi",
                            Name = "Tôm hùm nướng phô mai"
                        },
                        new
                        {
                            Id = 22,
                            DishId = "d-022",
                            LanguageCode = "vi",
                            Name = "Cua rang me"
                        },
                        new
                        {
                            Id = 23,
                            DishId = "d-023",
                            LanguageCode = "vi",
                            Name = "Ghẹ hấp bia"
                        },
                        new
                        {
                            Id = 24,
                            DishId = "d-024",
                            LanguageCode = "vi",
                            Name = "Mực chiên giòn"
                        },
                        new
                        {
                            Id = 25,
                            DishId = "d-025",
                            LanguageCode = "vi",
                            Name = "Cá mú hấp Hồng Kông"
                        },
                        new
                        {
                            Id = 26,
                            DishId = "d-026",
                            LanguageCode = "vi",
                            Name = "Ốc len xào dừa"
                        },
                        new
                        {
                            Id = 27,
                            DishId = "d-027",
                            LanguageCode = "vi",
                            Name = "Ốc bươu xào sả ớt"
                        },
                        new
                        {
                            Id = 28,
                            DishId = "d-028",
                            LanguageCode = "vi",
                            Name = "Sò điệp nướng mỡ hành"
                        },
                        new
                        {
                            Id = 29,
                            DishId = "d-029",
                            LanguageCode = "vi",
                            Name = "Ốc giác luộc"
                        },
                        new
                        {
                            Id = 30,
                            DishId = "d-030",
                            LanguageCode = "vi",
                            Name = "Nghêu nướng mỡ hành"
                        },
                        new
                        {
                            Id = 31,
                            DishId = "d-031",
                            LanguageCode = "vi",
                            Name = "Bò né truyền thống"
                        },
                        new
                        {
                            Id = 32,
                            DishId = "d-032",
                            LanguageCode = "vi",
                            Name = "Bò bít tết Úc"
                        },
                        new
                        {
                            Id = 33,
                            DishId = "d-033",
                            LanguageCode = "vi",
                            Name = "Bò lúc lắc khoai tây"
                        },
                        new
                        {
                            Id = 34,
                            DishId = "d-034",
                            LanguageCode = "vi",
                            Name = "Mì Ý bò bằm"
                        },
                        new
                        {
                            Id = 35,
                            DishId = "d-035",
                            LanguageCode = "vi",
                            Name = "Bánh mì chảo"
                        },
                        new
                        {
                            Id = 36,
                            DishId = "d-036",
                            LanguageCode = "vi",
                            Name = "Bánh tráng trộn đặc biệt"
                        },
                        new
                        {
                            Id = 37,
                            DishId = "d-037",
                            LanguageCode = "vi",
                            Name = "Bánh tráng nướng"
                        },
                        new
                        {
                            Id = 38,
                            DishId = "d-038",
                            LanguageCode = "vi",
                            Name = "Bánh tráng cuốn bò bía"
                        },
                        new
                        {
                            Id = 39,
                            DishId = "d-039",
                            LanguageCode = "vi",
                            Name = "Tré trộn rau răm"
                        },
                        new
                        {
                            Id = 40,
                            DishId = "d-040",
                            LanguageCode = "vi",
                            Name = "Gỏi khô bò"
                        });
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.ShopModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = "s-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "shop_01.jpg",
                            IsVisited = false,
                            Latitude = 10.75895,
                            Longitude = 106.70945,
                            Rating = 4.7999999999999998,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "shop_02.jpg",
                            IsVisited = false,
                            Latitude = 10.76042,
                            Longitude = 106.70589,
                            Rating = 4.5,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "shop_03.jpg",
                            IsVisited = false,
                            Latitude = 10.75933,
                            Longitude = 106.70814,
                            Rating = 4.2000000000000002,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-004",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "shop_04.jpg",
                            IsVisited = false,
                            Latitude = 10.758699999999999,
                            Longitude = 106.709,
                            Rating = 4.2999999999999998,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-005",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "shop_05.jpg",
                            IsVisited = false,
                            Latitude = 10.7591,
                            Longitude = 106.7093,
                            Rating = 4.5999999999999996,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-006",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "shop_06.jpg",
                            IsVisited = false,
                            Latitude = 10.758850000000001,
                            Longitude = 106.70869999999999,
                            Rating = 4.0999999999999996,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-007",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "shop_07.jpg",
                            IsVisited = false,
                            Latitude = 10.759600000000001,
                            Longitude = 106.7075,
                            Rating = 4.4000000000000004,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-008",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "shop_08.jpg",
                            IsVisited = false,
                            Latitude = 10.7598,
                            Longitude = 106.70699999999999,
                            Rating = 4.0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.ShopTranslationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("ShopId");

                    b.ToTable("ShopTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "534 Vĩnh Khánh, Phường 8, Quận 4",
                            Description = "Quán ốc nổi tiếng nhất nhì Sài Gòn, nằm trong Michelin Guide 2024. Không gian bình dân nhưng ốc luôn tươi sống, nước chấm đậm đà.",
                            LanguageCode = "vi",
                            Name = "Ốc Oanh 1",
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "232/123 Vĩnh Khánh, Phường 6, Quận 4",
                            Description = "Chi nhánh của thương hiệu ốc Đào nổi tiếng, nước sốt đậm đà, không gian rộng rãi, phù hợp nhóm bạn.",
                            LanguageCode = "vi",
                            Name = "Ốc Đào II",
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "395 Vĩnh Khánh, Phường 8, Quận 4",
                            Description = "Quán ốc bình dân với không khí nhộn nhịp đặc trưng của phố ẩm thực. Giá cả hợp lý, menu phong phú.",
                            LanguageCode = "vi",
                            Name = "Ốc Vũ",
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "478 Vĩnh Khánh, Phường 8, Quận 4",
                            Description = "Chuyên lẩu dê và các món dê nướng. Thịt dê tươi, không hôi, nước lẩu thơm ngon đậm vị thuốc bắc.",
                            LanguageCode = "vi",
                            Name = "Lẩu Dê Vĩnh Khánh",
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "502 Vĩnh Khánh, Phường 8, Quận 4",
                            Description = "Quán hải sản bình dân với bể hải sản tươi sống ngay trước quán. Tôm hùm, cua ghẹ luôn có sẵn.",
                            LanguageCode = "vi",
                            Name = "Hải Sản Bé Xu",
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "420 Vĩnh Khánh, Phường 8, Quận 4",
                            Description = "Ốc len xào dừa là đặc sản. Quán nhỏ nhưng đông khách, phục vụ nhanh, giá sinh viên.",
                            LanguageCode = "vi",
                            Name = "Quán Ốc Thúy",
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "350 Vĩnh Khánh, Phường 6, Quận 4",
                            Description = "Chuyên bò né, bít tết và các món ăn sáng kiểu Sài Gòn. Trứng ốp la, pate, bánh mì nóng giòn.",
                            LanguageCode = "vi",
                            Name = "Bò Né 3 Ngon",
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "300 Vĩnh Khánh, Phường 6, Quận 4",
                            Description = "Xe bánh tráng trộn nổi tiếng đầu đường. Bánh tráng giòn, nước sốt chua cay đặc biệt, topping đầy đủ.",
                            LanguageCode = "vi",
                            Name = "Bánh Tráng Trộn Cô Ba",
                            ShopId = "s-008"
                        });
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.DishModel", b =>
                {
                    b.HasOne("FoodTour_WebAdmin.Api.Models.ShopModel", "Shop")
                        .WithMany("Dishes")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.DishTranslationModel", b =>
                {
                    b.HasOne("FoodTour_WebAdmin.Api.Models.DishModel", "Dish")
                        .WithMany("DishTranslations")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.ShopTranslationModel", b =>
                {
                    b.HasOne("FoodTour_WebAdmin.Api.Models.ShopModel", "Shop")
                        .WithMany("ShopTranslations")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.DishModel", b =>
                {
                    b.Navigation("DishTranslations");
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.ShopModel", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("ShopTranslations");
                });
#pragma warning restore 612, 618
        }
    }
}
