// <auto-generated />
using System;
using FoodTour_WebAdmin.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodTour_WebAdmin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309173808_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.Dish", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ShopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = "d-001",
                            ImageUrl = "dish_01.jpg",
                            Name = "Càng ghẹ rang muối",
                            Price = 120000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-002",
                            ImageUrl = "dish_02.jpg",
                            Name = "Hào nướng phô mai",
                            Price = 50000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-003",
                            ImageUrl = "dish_03.jpg",
                            Name = "Nghêu hấp Thái",
                            Price = 120000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-004",
                            ImageUrl = "dish_04.jpg",
                            Name = "Bạch tuộc nướng muối ớt",
                            Price = 160000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-005",
                            ImageUrl = "dish_05.jpg",
                            Name = "Chem chép xào tỏi",
                            Price = 120000.0,
                            ShopId = "s-001"
                        },
                        new
                        {
                            Id = "d-006",
                            ImageUrl = "dish_01.jpg",
                            Name = "Ốc hương rang muối ớt",
                            Price = 110000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-007",
                            ImageUrl = "dish_02.jpg",
                            Name = "Ốc hương xào bơ",
                            Price = 110000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-008",
                            ImageUrl = "dish_03.jpg",
                            Name = "Sò huyết xào tỏi",
                            Price = 110000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-009",
                            ImageUrl = "dish_04.jpg",
                            Name = "Nghêu hấp sả",
                            Price = 80000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-010",
                            ImageUrl = "dish_05.jpg",
                            Name = "Ốc mỡ xào me",
                            Price = 110000.0,
                            ShopId = "s-002"
                        },
                        new
                        {
                            Id = "d-011",
                            ImageUrl = "dish_01.jpg",
                            Name = "Lưỡi vịt Sapo",
                            Price = 100000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-012",
                            ImageUrl = "dish_02.jpg",
                            Name = "Ốc tỏi nướng mắm",
                            Price = 60000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-013",
                            ImageUrl = "dish_03.jpg",
                            Name = "Răng mực rang muối",
                            Price = 60000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-014",
                            ImageUrl = "dish_04.jpg",
                            Name = "Bò lúc lắc",
                            Price = 110000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-015",
                            ImageUrl = "dish_05.jpg",
                            Name = "Khoai tây chiên",
                            Price = 50000.0,
                            ShopId = "s-003"
                        },
                        new
                        {
                            Id = "d-016",
                            ImageUrl = "dish_01.jpg",
                            Name = "Lẩu dê nấm",
                            Price = 250000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-017",
                            ImageUrl = "dish_02.jpg",
                            Name = "Dê nướng tảng",
                            Price = 180000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-018",
                            ImageUrl = "dish_03.jpg",
                            Name = "Dê xào lăn",
                            Price = 150000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-019",
                            ImageUrl = "dish_04.jpg",
                            Name = "Cháo dê đậu xanh",
                            Price = 60000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-020",
                            ImageUrl = "dish_05.jpg",
                            Name = "Tiết canh dê",
                            Price = 80000.0,
                            ShopId = "s-004"
                        },
                        new
                        {
                            Id = "d-021",
                            ImageUrl = "dish_01.jpg",
                            Name = "Tôm hùm nướng phô mai",
                            Price = 450000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-022",
                            ImageUrl = "dish_02.jpg",
                            Name = "Cua rang me",
                            Price = 320000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-023",
                            ImageUrl = "dish_03.jpg",
                            Name = "Ghẹ hấp bia",
                            Price = 200000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-024",
                            ImageUrl = "dish_04.jpg",
                            Name = "Mực chiên giòn",
                            Price = 130000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-025",
                            ImageUrl = "dish_05.jpg",
                            Name = "Cá mú hấp Hồng Kông",
                            Price = 380000.0,
                            ShopId = "s-005"
                        },
                        new
                        {
                            Id = "d-026",
                            ImageUrl = "dish_01.jpg",
                            Name = "Ốc len xào dừa",
                            Price = 70000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-027",
                            ImageUrl = "dish_02.jpg",
                            Name = "Ốc bươu xào sả ớt",
                            Price = 60000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-028",
                            ImageUrl = "dish_03.jpg",
                            Name = "Sò điệp nướng mỡ hành",
                            Price = 90000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-029",
                            ImageUrl = "dish_04.jpg",
                            Name = "Ốc giác luộc",
                            Price = 80000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-030",
                            ImageUrl = "dish_05.jpg",
                            Name = "Nghêu nướng mỡ hành",
                            Price = 70000.0,
                            ShopId = "s-006"
                        },
                        new
                        {
                            Id = "d-031",
                            ImageUrl = "dish_01.jpg",
                            Name = "Bò né truyền thống",
                            Price = 65000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-032",
                            ImageUrl = "dish_02.jpg",
                            Name = "Bò bít tết Úc",
                            Price = 120000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-033",
                            ImageUrl = "dish_03.jpg",
                            Name = "Bò lúc lắc khoai tây",
                            Price = 95000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-034",
                            ImageUrl = "dish_04.jpg",
                            Name = "Mì Ý bò bằm",
                            Price = 75000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-035",
                            ImageUrl = "dish_05.jpg",
                            Name = "Bánh mì chảo",
                            Price = 55000.0,
                            ShopId = "s-007"
                        },
                        new
                        {
                            Id = "d-036",
                            ImageUrl = "dish_01.jpg",
                            Name = "Bánh tráng trộn đặc biệt",
                            Price = 30000.0,
                            ShopId = "s-008"
                        },
                        new
                        {
                            Id = "d-037",
                            ImageUrl = "dish_02.jpg",
                            Name = "Bánh tráng nướng",
                            Price = 25000.0,
                            ShopId = "s-008"
                        },
                        new
                        {
                            Id = "d-038",
                            ImageUrl = "dish_03.jpg",
                            Name = "Bánh tráng cuốn bò bía",
                            Price = 35000.0,
                            ShopId = "s-008"
                        },
                        new
                        {
                            Id = "d-039",
                            ImageUrl = "dish_04.jpg",
                            Name = "Tré trộn rau răm",
                            Price = 40000.0,
                            ShopId = "s-008"
                        },
                        new
                        {
                            Id = "d-040",
                            ImageUrl = "dish_05.jpg",
                            Name = "Gỏi khô bò",
                            Price = 45000.0,
                            ShopId = "s-008"
                        });
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.Shop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = "s-001",
                            Address = "534 Vĩnh Khánh, Phường 8, Quận 4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quán ốc nổi tiếng nhất nhì Sài Gòn, nằm trong Michelin Guide 2024. Không gian bình dân nhưng ốc luôn tươi sống, nước chấm đậm đà.",
                            ImageUrl = "shop_01.jpg",
                            IsVisited = false,
                            Latitude = 10.75895,
                            Longitude = 106.70945,
                            Name = "Ốc Oanh 1",
                            Rating = 4.7999999999999998,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-002",
                            Address = "232/123 Vĩnh Khánh, Phường 6, Quận 4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chi nhánh của thương hiệu ốc Đào nổi tiếng, nước sốt đậm đà, không gian rộng rãi, phù hợp nhóm bạn.",
                            ImageUrl = "shop_02.jpg",
                            IsVisited = false,
                            Latitude = 10.76042,
                            Longitude = 106.70589,
                            Name = "Ốc Đào II",
                            Rating = 4.5,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-003",
                            Address = "395 Vĩnh Khánh, Phường 8, Quận 4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quán ốc bình dân với không khí nhộn nhịp đặc trưng của phố ẩm thực. Giá cả hợp lý, menu phong phú.",
                            ImageUrl = "shop_03.jpg",
                            IsVisited = false,
                            Latitude = 10.75933,
                            Longitude = 106.70814,
                            Name = "Ốc Vũ",
                            Rating = 4.2000000000000002,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-004",
                            Address = "478 Vĩnh Khánh, Phường 8, Quận 4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chuyên lẩu dê và các món dê nướng. Thịt dê tươi, không hôi, nước lẩu thơm ngon đậm vị thuốc bắc.",
                            ImageUrl = "shop_04.jpg",
                            IsVisited = false,
                            Latitude = 10.758699999999999,
                            Longitude = 106.709,
                            Name = "Lẩu Dê Vĩnh Khánh",
                            Rating = 4.2999999999999998,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-005",
                            Address = "502 Vĩnh Khánh, Phường 8, Quận 4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quán hải sản bình dân với bể hải sản tươi sống ngay trước quán. Tôm hùm, cua ghẹ luôn có sẵn.",
                            ImageUrl = "shop_05.jpg",
                            IsVisited = false,
                            Latitude = 10.7591,
                            Longitude = 106.7093,
                            Name = "Hải Sản Bé Xu",
                            Rating = 4.5999999999999996,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-006",
                            Address = "420 Vĩnh Khánh, Phường 8, Quận 4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ốc len xào dừa là đặc sản. Quán nhỏ nhưng đông khách, phục vụ nhanh, giá sinh viên.",
                            ImageUrl = "shop_06.jpg",
                            IsVisited = false,
                            Latitude = 10.758850000000001,
                            Longitude = 106.70869999999999,
                            Name = "Quán Ốc Thúy",
                            Rating = 4.0999999999999996,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-007",
                            Address = "350 Vĩnh Khánh, Phường 6, Quận 4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chuyên bò né, bít tết và các món ăn sáng kiểu Sài Gòn. Trứng ốp la, pate, bánh mì nóng giòn.",
                            ImageUrl = "shop_07.jpg",
                            IsVisited = false,
                            Latitude = 10.759600000000001,
                            Longitude = 106.7075,
                            Name = "Bò Né 3 Ngon",
                            Rating = 4.4000000000000004,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "s-008",
                            Address = "300 Vĩnh Khánh, Phường 6, Quận 4",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xe bánh tráng trộn nổi tiếng đầu đường. Bánh tráng giòn, nước sốt chua cay đặc biệt, topping đầy đủ.",
                            ImageUrl = "shop_08.jpg",
                            IsVisited = false,
                            Latitude = 10.7598,
                            Longitude = 106.70699999999999,
                            Name = "Bánh Tráng Trộn Cô Ba",
                            Rating = 4.0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.Dish", b =>
                {
                    b.HasOne("FoodTour_WebAdmin.Api.Models.Shop", "Shop")
                        .WithMany("Dishes")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("FoodTour_WebAdmin.Api.Models.Shop", b =>
                {
                    b.Navigation("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
