name: Build and Deploy FoodTour APK

on:
  push:
    branches: [ "main" ] # Nó sẽ chạy mỗi khi bạn push code lên nhánh main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui-android

    - name: Restore dependencies
      run: dotnet restore FoodTour.Mobile/FoodTour.Mobile.csproj

    - name: Build and Publish APK
      run: |
        dotnet publish FoodTour.Mobile/FoodTour.Mobile.csproj -f net9.0-android -c Release -r android-arm64 --self-contained true /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=foodtour.keystore /p:AndroidSigningKeyAlias=${{ secrets.KEY_ALIAS }} /p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }} /p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }}

    - name: Upload to Supabase Storage
      shell: pwsh
      run: |
        # Lục soát toàn bộ thư mục FoodTour.Mobile để tìm file -Signed.apk
        $filePath = Get-ChildItem -Path "FoodTour.Mobile" -Filter "*-Signed.apk" -Recurse | Select-Object -First 1 -ExpandProperty FullName
        
        Write-Host "Đã tìm thấy file APK tại: $filePath"
            
        # Link API của bạn
        $url = "${{ secrets.SUPABASE_URL }}/storage/v1/object/app/foodtour.apk"
            
        # Lệnh đẩy file lên và ghi đè (upsert)
        Invoke-RestMethod -Uri $url `
          -Method Post `
          -InFile $filePath `
          -ContentType "application/vnd.android.package-archive" `
          -Headers @{ 
            "Authorization" = "Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}";
            "apikey" = "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}";
            "x-upsert" = "true" 
          }